### ISSUE TITLE
Library doesn't seem to refresh the access token (OAuth2)

### ISSUE THREAD

**Issue by ile** [googleapis/google-auth-library-nodejs#1013]
- OS: Ubuntu 20.04 LTS
  - Node.js version: v12.16.1
  - npm version: 6.14.4
  - `google-auth-library` version: 6.0.5

#### Steps to reproduce

I'm trying to use this code to refresh the tokens, but nothing happens. Not sure if I'm doing something wrong? As I said [in the other issue](https://github.com/googleapis/google-auth-library-nodejs/issues/1006), it's not 100 % clear how to use this library (still isn't I'm afraid – also the sample code in the repository wasn't quite clear).

```js

const { OAuth2Client } = require('google-auth-library');

const credentials = {
	access_token: 'removed',
	refresh_token: 'removed',
	scope: 'https://mail.google.com/',
	token_type: 'Bearer',
	expiry_date: 1594943369086
}

const keys = {
	"client_id":"removed",
	"client_secret":"removed",
	"REDIRECT_URL": 'https://oauth.mydomain.dev/'
}


const client = new OAuth2Client(
	keys.client_id,
	keys.client_secret,
	keys.REDIRECT_URL
);

client.setCredentials(credentials);

client.on('tokens', (tokens) => {
	console.log('got tokens', tokens);
});

// To make node not exit
setInterval(( () => {} ), 1000 * 60 * 60);

```

So, this never goes into the 'tokens' callback.

I have been able to refresh the tokens by calling `client.refreshAccessTokenAsync()` but I don't think it's the right way.

Thank you.

**Comment by bcoe** [comment]
@ile tokens should be refreshed automatically when a request is made and they are expired. Are you able to make requests, just the token refresh callback was not invoked?

**Comment by JustinBeckwith** [comment]
Greetings @ile!  The tokens handler here never gets called because that code never asks for tokens :) Most of the token management in this library is automatic.  See:
https://github.com/googleapis/google-auth-library-nodejs#choosing-the-correct-credential-type-automatically

In that example, the call to `client.request` asks for tokens under the hood before making the request.  If the access token needs to be refreshed at that stage, the client will go ask for them, and invoke that handler.  If you can share specifically what you're trying to do, we'd happy to point towards a doc or sample that helps!
