### ISSUE TITLE
GoogleAuth.sign does not work with ExternalCredentials

### ISSUE THREAD

**Issue by clhuang** [googleapis/google-auth-library-nodejs#1215]
#### Environment details

  - OS: Mac OS 11.4
  - Node.js version: 14.16.1
  - npm version: 6.14.12
  - `google-auth-library` version: 7.3.0

#### Steps to reproduce
```ts
const { GoogleAuth } = require('google-auth-library');

const auth = new GoogleAuth({ keyFilename: './clientLibraryConfig.json' });
auth.sign('abc').then(console.log); // fails
```
output:
```
(node:76183) UnhandledPromiseRejectionWarning: Error: Cannot sign data without `client_email`.
    at GoogleAuth.sign (/Users/calvinhuang/scale/gcptest/node_modules/google-auth-library/build/src/auth/googleauth.js:638:19)
```
Attempting to use workload identity federation with cloud storage signing does not work because of this, where clientLibraryConfig.json is the config retrieved from the workload identity pools page.

it is possible to work around with a bit of a hack:

```ts
const { GoogleAuth } = require('google-auth-library');

const auth = new GoogleAuth({ keyFilename: './clientLibraryConfig.json' });
(async () => {
  await auth.getClient();
  auth.jsonContent = { client_email: 'service-account-email' };
  await auth.sign('abc').then(console.log);
})()
```

**Comment by bojeil-google** [comment]
Hey @clhuang, external account creds currently do not support signing blobs. The implementation currently depends on service account keys or need the [service account email](https://github.com/googleapis/google-auth-library-nodejs/blob/bbcc9d3daf3822700120220c1daff26a2e709894/src/auth/googleauth.ts#L882) in order to call `signBlob` which is why you are seeing this error.
I think we can update the implementation to get the service account email from the service account impersonation URL if available or otherwise error.
