### ISSUE TITLE
Recommended Electron oauth2 flow is no longer valid.

### ISSUE THREAD

**Issue by minht11** [googleapis/google-auth-library-nodejs#1411]
From August 2022 Google oauth2 iOS key will [no longer support localhost redirects](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html), this was a recommended way for Electron apps to use this library and still is inside the [docs](https://github.com/googleapis/google-auth-library-nodejs#oauth2-with-installed-apps-electron).

Given the policy changes what is the new recommended alternative? Just publishing client secret inside the app code?

**Comment by cronon** [comment]
I've just faced the same problem, has anybody found a solution yet?

**Comment by komret** [comment]
We played it extra safe and created a backend authorization service so that we did not have to expose the `client_secret`, here's the implementation: https://github.com/trezor/trezor-suite/pull/5669. Super annoying, especially if you do not need a backend otherwise.

**Comment by Theplayer592** [comment]
yh i've run into this problem recently too, and don't already have a backend. I'd much prefer to not have to create a whole sever just for this, so an alternative recommendation would be great.

**Comment by danielbankhead** [comment]
Hey folks - we're working on improving support for this library on Electron. For now I'll remove this confusing documentation.

Additionally, if you don't want to spin up a separate backend (understandable) you can use GIS's OAuth 2 implicit flow and use its access token for requests: https://developers.google.com/identity/oauth2/web/guides/use-token-model. It's a bit tricky to wire-up with this library, but it is possible.

**Comment by Theplayer592** [comment]
how do you get around google's insistance on a javascript origin? Electron doesn't really have a URL

**Comment by hrueger** [comment]
Just as another usecase which is not possible with the current limitations:

I'm working on @cpvalente's https://github.com/cpvalente/ontime to provide support for syncing with google sheets. Since it is an open-source (Electron) app, we cannot include a client secret (not even as a secret at build time, since it can be unpacked easily). Also, we can't require users to create their own google cloud project, setup api keys or oauth and whatnot because that is just too complicated.

> Electron doesn't really have a URL

Ontime can be used directly in the electron ui or by pointing a browser to the webserver it automatically hosts. Therefore, we do have a url. However, users can configure the port and when accessing it externally, we don't know the ip in advance. Therefore, we can't set valid web origins in our cloud project...

**Comment by danielbankhead** [comment]
Here's a public tracking issue:
- https://github.com/googleapis/google-auth-library-nodejs/issues/1638

I've closed this via #1635 as outdated documentation was the original issue. In the meantime we're actively working on alternate runtime support.
