### ISSUE TITLE
Breaking Changes Explanation for 9.0.0

### ISSUE THREAD

**Issue by mmilleruva** [googleapis/google-auth-library-nodejs#1626]
I am upgrading my site to use 9.0.0 and I see a list of breaking changes documented here:
https://github.com/googleapis/google-auth-library-nodejs/releases

My question is what do they break and what changes do developers need to incorporate to resolve those breaking changes?

I have tried to review the individual PRs to understand what the breaking change is, but most of them have no description, or I don't have access to the documentation referenced.

**Comment by danielbankhead** [comment]
Hey @mmilleruva,

Excellent question - here's collection of breaking changes and how to adapt to the latest version:

- We've dropped support for Node 12 and require Node 14+.
- We've dropped support for `.p12` certs https://github.com/googleapis/node-gtoken/pull/452
  - They have been long deprecated and removing support greatly reduces the size of all of the libraries as we can drop `node-forge` as a dependency altogether
- We use a more generic `Transporter` type rather than `DefaultTransporter` across the clients. This means if someone is relying on `DefaultTransporter` properties, they should explicitly instantiate and set that as an `AuthClient`'s transport https://github.com/googleapis/google-auth-library-nodejs/pull/1406#issuecomment-1145207392
- We drop support for browsers without [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) support https://github.com/googleapis/google-auth-library-nodejs/pull/1583

In general, we don't expect most folks to be affected.
