### ISSUE TITLE
OAuth2Client.getIdToken()

### ISSUE THREAD

**Issue by mbrevda** [googleapis/google-auth-library-nodejs#1726]
it would be great if a `OAuth2Client.getIdToken()` method could be added. Currently, `OAuth2Client.getAccessToken()` exists, which allows getting an access token with automatic refresh if necessary. It would be handy if this were available for other tokens as well, such as the id token. Alternatively, a method that auto-refreshed and returned _all_ credentials could be just as useful.

**Comment by danielbankhead** [comment]
This was historically done by design as not all classes extending from OAuth2Client had, or should have, idTokens. Here are a few that do today (via `fetchIdToken`):

https://github.com/googleapis/google-auth-library-nodejs/blob/1a7ba87d42661e5b51c6751ccbbc66e226d9e830/src/auth/computeclient.ts#L103-L122

https://github.com/googleapis/google-auth-library-nodejs/blob/1a7ba87d42661e5b51c6751ccbbc66e226d9e830/src/auth/impersonated.ts#L216-L236

https://github.com/googleapis/google-auth-library-nodejs/blob/1a7ba87d42661e5b51c6751ccbbc66e226d9e830/src/auth/jwtclient.ts#L189-L207

By chance if you are looking for this functionality in the `UserRefreshClient`, which extends OAuth2Client, that can be tracked here:
- https://github.com/googleapis/google-auth-library-nodejs/issues/876
