### ISSUE TITLE
Wrong detection of isBrowser in an Adobe CEP Extension

### ISSUE THREAD

**Issue by thibaultbrocheton** [googleapis/google-auth-library-nodejs#682]
Hello,

I have an issue since you introduced the isBrowser.js file (had the problem in gaxios too with stream API, but used a workaround), allowing two different behavior depending if you're on browser or nodejs.
This file exports this function:

```javascript
function isBrowser() {
    return typeof (window) !== 'undefined';
}
```

I'm in a tricky context: i'm developping an extension for an Adobe Product (After Effect) using Adobe CEP Extension. In this system, a chromium browser start a nodejs server. So their context is shared, in my nodejs I have the window Object.
So the isBrower function return true. It's problematic for the decodeBase64StringUtf8 function, because it's using the browser function, and it fails to decode the token enveloppe of an Oauth Response.

I know my context is particular, would you have any advice to help with this situation ?
I can't delete the window object (it is read only, and I need it in my browser execution)
I would like to avoid to edit the node_modules files, or fork the project

Thanks in advance !

**Comment by JustinBeckwith** [comment]
Hey there!  Happy to help.  Can you check something for me?  What's the type of `window.document` in this environment?  

This is turning out to be a comically complicated problem 😆 I'm thinking of standardizing our modules on something like:
https://github.com/flexdinesh/browser-or-node/blob/master/src/index.js

fyi @alexander-fenster @bcoe

**Comment by thibaultbrocheton** [comment]
Hey @JustinBeckwith,

just tried, the typeof is object for both window and window.document
it's terrible because actually I'm in a browser. And i'm in a nodejs context.
I can access my dom from my nodejs server, and my server from my browser...

As a workaround, I added a postinstall script to my package.json, replacing your isbrowser.js file with a custom one (which basically juste return false in the function).

I tested the 3 vars defined in the browser-or-node package, here the returns:
isBrowser: true
isWebWorker: false
isNode: true

Sooo... If you integrate this kind of check, the program will still have to make a choice: browser or node

**Comment by JustinBeckwith** [comment]
Yeah I really don't know what to do here 😨  The only thing I can think of is to create separate entry points in the module, and ask authors who want the web version to be very explicit about that choice.  The problem is that module bundlers like browserify and webpack will likely not work well here.  

Are you happy with the solution you came up with?  Because that may be the best bet.

**Comment by thibaultbrocheton** [comment]
Hey,
my workaround works pretty well, and is automatic, so it's ok for me. I will just have to check when I update my dependencies that you don't change this file :)

I write my solution here, if somebody (or myself ^^) arrive later on this page

```
"scripts": {
    "postinstall": "node ../scripts/is-browser-hack.js"
  },
```

```
'use strict';

const fs = require('fs');
const path = require('path');

const isBrowserPath = path.join(__dirname, '../server/node_modules/google-auth-library/build/src/isbrowser.js');
const isBrowserHack = `"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
function isBrowser() {
    return false;
}
exports.isBrowser = isBrowser;
//# sourceMappingURL=isbrowser.js.map
`;

console.log("HACK: Replacing " + isBrowserPath + " by hacked version to ensure isBrowser returns false...");
fs.writeFileSync(isBrowserPath, isBrowserHack);
console.log("HACK: Replacing done.");
```

Thank you for your time on my issue !

**Comment by alexander-fenster** [comment]
Hi @thibaultbrocheton,

I'm pretty sure it's not the first complicated environment we've met since introducing browser support, and I believe we'll eventually need to replace `isBrowser` with something more clever. Speaking about your particular environment, do you think there are any special globals to take a look for, specific for your environment (and not just for Node.js or browser)?

I checked some documentation for Adobe CEP and it _seems_ we can check for `typeof File` and `typeof XML` (and consider the environment to be a Node if they exist, even if `window` also exists). Can you check if these globals are defined?

**Comment by thibaultbrocheton** [comment]
Hey @alexander-fenster,

When activating nodejs support in an adobe cep extension, the cep_node global object is added.
cf:  https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#nodejs

I think it's the best choice to target this environment.
FYI I was able to find a function named File, but no XML.
