### ISSUE TITLE
OAuth2 - Facing an issue while retrieving the access token

### ISSUE THREAD

**Issue by vinoth-kumar-siva** [googleapis/google-auth-library-nodejs#745]
Scenario: 
While authenticating it has been successfully redirecting to my redirect URI,  and I can able to see the code in browser tab's the query string. But it's keep's on trying to get the access token and returns a timeout error.

Code:

function getAuthenticatedClient() {
    return new Promise((resolve, reject) => {
        const oAuth2Client = new OAuth2Client(
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com",
            "XXXXXXXXXXXXXXXXXXX",
            "https://google-auth-dev.localtunnel.me/signup"
        );
 
        const authorizeUrl = oAuth2Client.generateAuthUrl({
            access_type: 'offline',
            scope: 'https://www.googleapis.com/auth/plus.business.manage',
        });
 
        const server = http.createServer(async (req, res) => {
            try {
                if (req.url.indexOf('/oauth2callback') > -1) {
                    const qs = new url.URL(req.url, 'https://google-auth-dev.localtunnel.me/signup')
                        .searchParams;
                    const code = qs.get('code');
                    console.log(`Code is ${code}`);
                    server.destroy();
        
                    const r = await oAuth2Client.getToken(code);
                    oAuth2Client.setCredentials(r.tokens);
                    console.info('Tokens acquired.');
                    resolve(oAuth2Client);
                }
            } catch (e) {
                reject(e);
            }
        }).listen(8080, () => {
            opn(authorizeUrl, {wait: false}).then(cp => cp.unref());
        });
        destroyer(server);
    });
}
main().catch(console.error);

**Comment by bcoe** [comment]
@vinoth-kumar-siva what is your reason for connecting through `localtunnel.me`, I notice that this site has bad certificates, and I could imagine it potentially interfering with your client (and introducing a timeout).

Rather than using a site like `localtunnel`, I would instead set the callback URL to something like `127.0.0.1:5000`, where `5000` is the port of a service you are running locally. Since the token exchange happens in the web browser on your machine, there's no need for the upstream service to be able to directly connect to your service.
